// ============================================
// 极小圈子 模拟数据
// ============================================

const CIRCLES = [
  {
    id: 'c-oneos',
    name: 'OneOS 核心研发圈',
    topic: 'OneOS架构',
    topicIcon: '\u25C8',
    color: '#4F46E5',
    description: 'OneOS 产品核心团队的异步深度讨论空间。所有讨论自动沉淀为知识库。',
    memberCount: 8,
    maxMembers: 10,
    createdAt: '2025-11-20',
    creator: '马行远',
    role: 'creator',
    timeWindow: {
      type: 'weekday',
      label: '工作日 9:00 - 18:00',
      isOpenNow: true,
    },
    stats: {
      topics: 6,
      archived: 3,
      replies: 28,
    },
    permissions: {
      post: 'all',
      reply: 'all',
      restructure: 'admin',
    },
  },
  {
    id: 'c-thinking',
    name: '深度思考同频圈',
    topic: '哲学与认知',
    topicIcon: '\u03A8',
    color: '#9B6BA0',
    description: '一群真正同频的人，围绕哲学、认知、存在等话题，定期深度分享。不求多，但求深。',
    memberCount: 6,
    maxMembers: 10,
    createdAt: '2026-01-15',
    creator: '马行远',
    role: 'creator',
    timeWindow: {
      type: 'custom',
      label: '每周二、四晚 20:00 - 22:00',
      isOpenNow: false,
    },
    stats: {
      topics: 5,
      archived: 2,
      replies: 18,
    },
    permissions: {
      post: 'all',
      reply: 'all',
      restructure: 'admin',
    },
  },
];

// 成员
const CIRCLE_MEMBERS = {
  'c-oneos': [
    { id: 'm-me', name: '马行远', avatar: '马', role: 'creator', joinedAt: '2025-11-20' },
    { id: 'm-he', name: '何思齐', avatar: '何', role: 'admin', joinedAt: '2025-11-21' },
    { id: 'm-fang', name: '方墨言', avatar: '方', role: 'member', joinedAt: '2025-11-25' },
    { id: 'm-chen', name: '陈屿白', avatar: '陈', role: 'member', joinedAt: '2025-12-01' },
    { id: 'm-lin', name: '林知秋', avatar: '林', role: 'member', joinedAt: '2025-12-10' },
    { id: 'm-wanqing', name: '苏晚晴', avatar: '苏', role: 'member', joinedAt: '2026-01-05' },
    { id: 'm-zhou', name: '周予安', avatar: '周', role: 'member', joinedAt: '2026-02-14' },
    { id: 'm-tang', name: '唐予之', avatar: '唐', role: 'member', joinedAt: '2026-03-01' },
  ],
  'c-thinking': [
    { id: 'm-me', name: '马行远', avatar: '马', role: 'creator', joinedAt: '2026-01-15' },
    { id: 'm-lin', name: '林知秋', avatar: '林', role: 'admin', joinedAt: '2026-01-16' },
    { id: 'm-shen', name: '沈听澜', avatar: '沈', role: 'member', joinedAt: '2026-01-20' },
    { id: 'm-wanqing', name: '苏晚晴', avatar: '苏', role: 'member', joinedAt: '2026-01-22' },
    { id: 'm-yu', name: '于建飞', avatar: '于', role: 'member', joinedAt: '2026-02-01' },
    { id: 'm-gu', name: '顾野松', avatar: '顾', role: 'member', joinedAt: '2026-02-15' },
  ],
};

// 话题文档
const CIRCLE_TOPICS = {
  'c-oneos': [
    {
      id: 't-001',
      title: '升维功能的交互设计讨论',
      author: '马行远',
      authorAvatar: '马',
      createdAt: '2026-03-15',
      lastUpdate: '3小时前',
      replyCount: 5,
      tags: ['升维', '交互设计'],
      pinned: true,
      archived: false,
      excerpt: '关于升维板块的核心交互，我想再深入讨论一下。现在的漏斗模型视觉上没问题，但用户感知不到"升维"这个动作本身...',
    },
    {
      id: 't-002',
      title: '人类节点系统的产品哲学',
      author: '何思齐',
      authorAvatar: '何',
      createdAt: '2026-03-10',
      lastUpdate: '1天前',
      replyCount: 3,
      tags: ['人类节点', '产品哲学'],
      pinned: true,
      archived: false,
      excerpt: '人类节点系统不是另一个社交网络。它是对"人在数字系统中如何存在"的一次彻底重构。我想聊聊背后的哲学基础...',
    },
    {
      id: 't-003',
      title: '语音板块：音色开放的边界在哪里',
      author: '苏晚晴',
      authorAvatar: '苏',
      createdAt: '2026-03-05',
      lastUpdate: '5天前',
      replyCount: 4,
      tags: ['语音', '隐私', '伦理'],
      pinned: false,
      archived: false,
      excerpt: '音色克隆这个功能很强大，但也带来了很多伦理问题。我想和大家讨论一下：音色开放的边界应该划在哪里？...',
    },
    {
      id: 't-006',
      title: '极小圈子的边界讨论',
      author: '马行远',
      authorAvatar: '马',
      createdAt: '2026-03-12',
      lastUpdate: '4天前',
      replyCount: 4,
      tags: ['圈子', '产品设计'],
      pinned: false,
      archived: false,
      excerpt: '圈子功能我们已经做了，但有几个边界问题我还在纠结：最多几人？能不能有消息模式？时间窗口是强制的还是建议的？...',
    },
    {
      id: 't-004',
      title: 'v1.0 功能范围确认',
      author: '马行远',
      authorAvatar: '马',
      createdAt: '2026-02-20',
      lastUpdate: '2周前',
      replyCount: 6,
      tags: ['版本规划'],
      pinned: false,
      archived: true,
      excerpt: 'v1.0 我们做什么、不做什么，需要达成共识。我先抛一个范围清单，大家来加减...',
    },
    {
      id: 't-005',
      title: '数据模型最终方案',
      author: '马行远',
      authorAvatar: '马',
      createdAt: '2026-01-20',
      lastUpdate: '1个月前',
      replyCount: 4,
      tags: ['技术架构'],
      pinned: false,
      archived: true,
      excerpt: '经过几轮讨论，数据模型基本定了。以本地 Markdown 为唯一数据结构，所有数据都存在文件系统里...',
    },
  ],
  'c-thinking': [
    {
      id: 't-101',
      title: '注意力残留：为什么我们很难深度思考',
      author: '林知秋',
      authorAvatar: '林',
      createdAt: '2026-03-14',
      lastUpdate: '2天前',
      replyCount: 3,
      tags: ['注意力', '深度工作'],
      pinned: true,
      archived: false,
      excerpt: '最近在读《深度工作》，里面有个概念叫"注意力残留"——从一个任务切换到另一个任务时，注意力并不会立刻完全转移...',
    },
    {
      id: 't-102',
      title: '知识升维到底升的是什么？',
      author: '马行远',
      authorAvatar: '马',
      createdAt: '2026-03-08',
      lastUpdate: '1周前',
      replyCount: 4,
      tags: ['知识论', '升维'],
      pinned: true,
      archived: false,
      excerpt: '关于"知识升维"，我最近有了一个新的理解。升维升的不是知识的量，而是认知的颗粒度。想和大家讨论一下...',
    },
    {
      id: 't-105',
      title: '慢的价值：为什么我们需要"等一等"',
      author: '于建飞',
      authorAvatar: '于',
      createdAt: '2026-03-01',
      lastUpdate: '2周前',
      replyCount: 3,
      tags: ['慢哲学', '音乐'],
      pinned: false,
      archived: false,
      excerpt: '我从音乐的角度聊聊"慢"。弹琴的人都知道，慢比快难。不是慢本身难，是在慢里保持张力和呼吸感难...',
    },
    {
      id: 't-103',
      title: '时间是最公平的东西',
      author: '沈听澜',
      authorAvatar: '沈',
      createdAt: '2026-02-28',
      lastUpdate: '3周前',
      replyCount: 2,
      tags: ['时间哲学', '存在主义'],
      pinned: false,
      archived: false,
      excerpt: '最近在想一个简单的问题：为什么时间对每个人都是公平的？因为时间不是资源，时间就是存在本身...',
    },
    {
      id: 't-104',
      title: '关于"主体性"的讨论',
      author: '马行远',
      authorAvatar: '马',
      createdAt: '2026-02-10',
      lastUpdate: '1个月前',
      replyCount: 5,
      tags: ['主体性', '产品哲学'],
      pinned: false,
      archived: true,
      excerpt: '"主体性至上"是OneOS的核心原则之一。但到底什么是主体性？我想和大家一起把这个概念讨论清楚...',
    },
  ],
};

// 话题详情内容（长文本单独存，避免和上面的结构混在一起）
const TOPIC_DETAILS = {
  't-001': {
    content: [
      '# 升维功能的交互设计讨论',
      '',
      '关于升维板块的核心交互，我想再深入讨论一下。',
      '',
      '## 核心问题',
      '',
      '现在的漏斗模型视觉上没问题，但用户感知不到"升维"这个动作本身。点一下按钮，结果就出来了——太简单了，缺少仪式感。',
      '',
      '升维不应该是一瞬间完成的事情。它应该是一个**过程**——用户看着自己的笔记被重新组织、被提炼、被升维。这个过程本身就是价值。',
      '',
      '## 我的想法',
      '',
      '把升维做成一个**12秒的渐进式动画**：',
      '',
      '1. 底层：原始笔记（零散的卡片）',
      '2. 向上流动：关键词提取、关联匹配',
      '3. 中层：结构重组、去重合并',
      '4. 顶层：精华凝结、升维完成',
      '',
      '每一层都有停顿，不是很快地一闪而过。就像泡茶一样，得等。',
      '',
      '## 为什么是12秒',
      '',
      '我和行远讨论过这个数字。8秒太快了，用户还没进入状态就结束了。15秒又太长，容易走神。12秒刚好——大约是三次深呼吸的时间。',
      '',
      '用户在这12秒里什么都不用做，就看着。',
      '',
      '现代人太着急了，什么都想要立刻有结果。升维这个功能就是要反其道而行之——让你慢下来，让你等，让你在等待中体会"提炼"这个过程本身。',
      '',
      '## 想听听大家的意见',
      '',
      '1. 这个方向对不对？',
      '2. 12秒是不是合适的时长？',
      '3. 动画过程中还可以加什么？',
      '',
      '---',
      '*这是一个产品哲学层面的讨论，不只是交互细节。*',
    ],
    replies: [
      {
        id: 'r-001', author: '何思齐', avatar: '何', createdAt: '2026-03-15',
        content: '方向完全同意。补充一点：12秒的等待里，如果什么信息都不给，用户可能会焦虑。建议在不同阶段给出极简的文字提示，比如"正在梳理关联...""正在凝结精华..."这样的。不是进度条那种，而是更有温度的文字。',
      },
      {
        id: 'r-002', author: '方墨言', avatar: '方', createdAt: '2026-03-15',
        content: '从视觉设计角度补充：升维动画的颜色应该从下到上逐渐变化。底层用冷色（数据层），顶层用暖色（智慧层）。颜色的渐变本身也在表达"升维"这个概念。',
      },
      {
        id: 'r-003', author: '林知秋', avatar: '林', createdAt: '2026-03-16',
        content: '我从哲学角度提个问题：如果升维的过程只是一个动画，用户会不会觉得"这只是个特效"，而不是真的在升维？\n\n我的建议是：动画过程中，用户可以看到自己的笔记真的在被重新组织——不是抽象的粒子效果，而是真的把用户写过的文字卡片一个个拎起来、归类、合并。这样用户才会觉得"哦，它真的在处理我的东西"，而不是播放一个预设好的动画。',
      },
      {
        id: 'r-004', author: '苏晚晴', avatar: '苏', createdAt: '2026-03-16',
        content: '知秋说得好。我补充：升维的结果不应该是系统给的"标准答案"，而应该是一个"建议"。用户可以修改、可以拒绝、可以保留自己的理解。\n\n主体性至上——这应该贯穿到升维功能里。AI 是辅助，不是替代。',
      },
      {
        id: 'r-005', author: '马行远', avatar: '马', createdAt: '2026-03-17',
        content: '感谢大家的讨论，非常有启发。总结一下共识方向：\n\n1. 12秒动画，分多层渐进\n2. 用真实笔记卡片做动画，不是抽象粒子\n3. 颜色从冷到暖渐变\n4. 过程中给极简的文字提示\n5. 结果是"建议"而非"标准答案"，用户可修改\n\n我整理一下，下个版本就按这个方向做。',
      },
    ],
  },
  't-002': {
    content: [
      '# 人类节点系统的产品哲学',
      '',
      '人类节点系统不是另一个社交网络。它是对"人在数字系统中如何存在"的一次彻底重构。',
      '',
      '## 为什么要做人类节点',
      '',
      '传统社交的逻辑：人 → 联系人列表 → 聊天框。人是中心，话题是附属。',
      '',
      '但这不符合真实的人际关系。现实中，我们是通过话题认识人的。因为共同喜欢音乐认识，因为一起做项目认识，因为一本书认识。',
      '',
      '所以 OneOS 的逻辑反过来：**话题才是中心，人只是知识图谱中的一种节点类型。**',
      '',
      '## 加好友的方式也要重写',
      '',
      '不是"我加你微信→进通讯录→随时骚扰你"，',
      '而是"我在某个话题下→添加人类节点→生成绑定该话题的邀请码→对方扫码通过→他直接出现在这个话题的图谱里"。',
      '',
      '所有沟通从话题切入，沟通内容自动归档到话题下，以 Markdown 文档形式存储。',
      '',
      '这样有什么好处？',
      '',
      '1. **没有骚扰**——想联系我，你得有个话题。没头没脑的消息不存在',
      '2. **关系有语境**——你知道这个人是在什么话题里认识的，为什么重要',
      '3. **自动沉淀**——所有沟通自动变成知识，不会浪费',
    ],
    replies: [
      {
        id: 'r-101', author: '马行远', avatar: '马', createdAt: '2026-03-10',
        content: '这个方向我非常认同。想补充一点：邀请码不仅绑定话题，还应该绑定权限层级。比如核心圈、合作圈、兴趣圈——不同的话题下，同一个人可以有不同的权限。',
      },
      {
        id: 'r-102', author: '陈屿白', avatar: '陈', createdAt: '2026-03-11',
        content: '作为投资人，我关心一个问题：这样的设计用户学习成本高不高？毕竟大家用了十几年微信，习惯已经形成了。\n\n从"联系人列表"到"人类节点+话题"，这个认知跳跃会不会太大？',
      },
      {
        id: 'r-103', author: '林知秋', avatar: '林', createdAt: '2026-03-12',
        content: '回屿白的问题：我觉得学习成本不是问题，因为这是一个更符合直觉的模型。\n\n你第一次见到一个人的时候，你不会把他存进"通讯录"然后就完事了。你记住的是"在什么场合认识的""聊了什么话题"。这个模型更接近人脑真实的记忆方式。\n\n微信的通讯录才是反直觉的——把活生生的人简化成一个名字加头像，剥离所有语境。',
      },
    ],
  },
  't-101': {
    content: [
      '# 注意力残留：为什么我们很难深度思考',
      '',
      '最近重读《深度工作》，有个概念每次读都有新体会：**注意力残留**。',
      '',
      '## 什么是注意力残留',
      '',
      '当你从任务A切换到任务B时，你的注意力并不会立刻完全转移到B上。有一部分注意力还"残留在"A任务上，在后台继续处理A的未竟之事。',
      '',
      '切换得越频繁，残留就越多，能真正投入到当前任务的注意力就越少。',
      '',
      '## 这就是为什么碎片化是深度思考的敌人',
      '',
      '不是我们变笨了，是我们的注意力被切成了碎片。每一次消息提示、每一次刷手机、每一次"看一眼就好"，都是在制造新的注意力残留。',
      '',
      '一天下来，你可能什么都没干，但累得不行——因为你的注意力一直在被拉扯。',
      '',
      '## 怎么办',
      '',
      '简单说：**减少切换次数**。',
      '',
      '但说起来容易做起来难。我最近在尝试的方法：',
      '',
      '1. 固定深度思考时间：每天早上8-10点，不看手机、不开电脑',
      '2. 单任务：同一时间只做一件事，做完再做下一件',
      '3. 数字极简：非必要的App通知全部关掉',
      '',
      '效果？刚开始很难受，坐立不安。坚持了两周之后，明显感觉思考的深度不一样了。',
    ],
    replies: [
      {
        id: 'r-501', author: '马行远', avatar: '马', createdAt: '2026-03-14',
        content: '注意力残留这个概念太重要了。我有个观察：很多人以为自己在"同时处理多件事"，其实只是在快速切换。切换的间隙，注意力残留堆积，效率不是加法，而是减法。\n\nOneOS 的设计哲学里，"零打扰"之所以是核心原则，就是因为我们相信——注意力是这个时代最稀缺的资源，应该被认真对待。',
      },
      {
        id: 'r-502', author: '沈听澜', avatar: '沈', createdAt: '2026-03-15',
        content: '分享一个我在读书会实践的方法：**"数字安息日"**。\n\n每周选一天，完全不用电子设备。不是为了复古，而是让注意力有一个彻底清空、重置的机会。\n\n第一天可能很难受，第二天你会发现脑子清楚了很多。到了第三天，会有很多很久没有过的想法冒出来——那些想法一直都在，只是平时被噪音盖住了。',
      },
      {
        id: 'r-503', author: '于建飞', avatar: '于', createdAt: '2026-03-16',
        content: '弹琴的人都有这个体会。一首曲子你练了很多遍，快弹的时候觉得弹得不错。一放慢，就发现到处都是问题。\n\n注意力也是一样——快的时候，你觉得自己在思考。慢下来，才发现自己只是在被念头牵着跑。',
      },
    ],
  },
};

// 知识库（已归档的话题）
function getKnowledgeBase(circleId) {
  const topics = CIRCLE_TOPICS[circleId] || [];
  return topics.filter(t => t.archived);
}

Object.assign(window, {
  CIRCLES,
  CIRCLE_MEMBERS,
  CIRCLE_TOPICS,
  TOPIC_DETAILS,
  getKnowledgeBase,
});
